#!/bin/bash
#SBATCH --job-name=gunc
#SBATCH --output=gunc.out
#SBATCH --error=gunc.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=12
#SBATCH --mem=25G
#SBATCH --partition=base
#SBATCH --time=5:00:00
#SBATCH --reservation=biol217

# load necessary modules
module load gcc12-env/12.1.0
module load micromamba
eval "$(micromamba shell hook --shell=bash)"
export MAMBA_ROOT_PREFIX=$WORK/.micromamba

cd $WORK

micromamba activate .micromamba/envs/00_anvio/

# loop quality control for all of the fastqc files in the path
# for file in /work_beegfs/sunam227/metagenomics/0_raw_reads/*.gz; do
#     fastqc "${file}" -o /work_beegfs/sunam227/metagenomics/0_raw_reads/quality_reads
# done


# fastp -i /work_beegfs/sunam227/metagenomics/0_raw_reads/BGR_130305_mapped_R1.fastq.gz -I /work_beegfs/sunam227/metagenomics/0_raw_reads/BGR_130305_mapped_R2.fastq.gz -R /work_beegfs/sunam227/metagenomics/0_raw_reads/reports/fastp305_report -o /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130305_clean_R1.fastq.gz -O /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130305_clean_R2.fastq.gz -t 6 -q 20
# fastp -i /work_beegfs/sunam227/metagenomics/0_raw_reads/BGR_130527_mapped_R1.fastq.gz -I /work_beegfs/sunam227/metagenomics/0_raw_reads/BGR_130527_mapped_R2.fastq.gz -R /work_beegfs/sunam227/metagenomics/0_raw_reads/reports/fastp527_report -o /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130527_clean_R1.fastq.gz -O /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130527_clean_R2.fastq.gz -t 6 -q 20
# fastp -i /work_beegfs/sunam227/metagenomics/0_raw_reads/BGR_130708_mapped_R1.fastq.gz -I /work_beegfs/sunam227/metagenomics/0_raw_reads/BGR_130708_mapped_R2.fastq.gz -R /work_beegfs/sunam227/metagenomics/0_raw_reads/reports/fastp708_report -o /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130708_clean_R1.fastq.gz -O /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130708_clean_R2.fastq.gz -t 6 -q 20



# cd /work_beegfs/sunam227/metagenomics/0_raw_reads/clean
# megahit -1 /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130305_clean_R1.fastq.gz -2 /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130305_clean_R2.fastq.gz --min-contig-len 1000 --presets meta-large -m 0.85 /work_beegfs/sunam227/metagenomics/0_raw_reads/assembly/ -t12
# megahit -1 /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130527_clean_R1.fastq.gz -2 /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130527_clean_R2.fastq.gz --min-contig-len 1000 --presets meta-large -m 0.85 /work_beegfs/sunam227/metagenomics/0_raw_reads/assembly/ -t12
# megahit -1 /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130708_clean_R1.fastq.gz -2 /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130708_clean_R2.fastq.gz --min-contig-len 1000 --presets meta-large -m 0.85 /work_beegfs/sunam227/metagenomics/0_raw_reads/assembly/ -t12


# megahit_toolkit contig2fastg 99 /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/megahit_out/final.contigs.fa > /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/megahit_out/final.contigs.fastg


# metaquast -t 6 -o /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/megahit_out/3_metaquast -m 1000 /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/megahit_out/final.contigs.fa

# anvi-script-reformat-fasta /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/megahit_out/final.contigs.fa -o /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/megahit_out/contigs.anvio.fa --min-len 1000 --simplify-names --report-file nameconversion.txt

# bowtie2-build /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/megahit_out/contigs.anvio.fa /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/megahit_out/contigs-anvio.fa.index

#bowtie2 --very-fast -x /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/megahit_out/contigs-anvio.fa.index -1 /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130305_clean_R1.fastq.gz -2 /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130305_clean_R2.fastq.gz -S /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/sample1.sam
#bowtie2 --very-fast -x /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/megahit_out/contigs-anvio.fa.index -1 /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130527_clean_R1.fastq.gz -2 /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130527_clean_R2.fastq.gz -S /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/sample2.sam
#bowtie2 --very-fast -x /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/megahit_out/contigs-anvio.fa.index -1 /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130708_clean_R1.fastq.gz -2 /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/BGR_130708_clean_R2.fastq.gz -S /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/sample3.sam

#samtools view -bS /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/sample1.sam > /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/sample1.bam
#samtools view -bS /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/sample2.sam > /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/sample2.bam
#samtools view -bS /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/sample3.sam > /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/sample3.bam


# For the contig Data Preperation
#anvi-gen-contigs-database -f /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/megahit_out/contigs.anvio.fa -o /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/contigs.db -n 'biol217'



# HMM search 
#cd /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/
#anvi-run-hmms -c contigs.db




# Sorting and indexing bam files
#cd /work_beegfs/sunam227/metagenomics/0_raw_reads/clean
#for file in *.bam; do anvi-init-bam $file -o "$file".sorted.bam; done


# creating anvio profile
#cd /work_beegfs/sunam227/metagenomics/0_raw_reads/clean
#anvi-profile -i sample1.bam.sorted.bam -c contigs.db --output-dir  /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/profile1
#anvi-profile -i sample2.bam.sorted.bam -c contigs.db --output-dir  /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/profile2
#anvi-profile -i sample3.bam.sorted.bam -c contigs.db --output-dir  /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/profile3

# merging profiles
#cd /work_beegfs/sunam227/metagenomics/0_raw_reads/clean
#anvi-merge ./profile1/PROFILE.db ./profile2/PROFILE2.db ./profile3/PROFILE3.db -o /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/mergedprof -c contigs.db --enforce-hierarchical-clustering

# Binning with Metabat2
#cd /work_beegfs/sunam227/metagenomics/0_raw_reads/clean
#anvi-cluster-contigs -p ./mergedprof/PROFILE.db -c contigs.db -C METABAT2 --driver metabat2 --just-do-it --log-file log-metabat2

#anvi-summarize -p ./mergedprof/PROFILE.db -c contigs.db -o SUMMARY_METABAT2 -C METABAT2

# binning with MaxBin2
#cd /work_beegfs/sunam227/metagenomics/0_raw_reads/clean
#anvi-cluster-contigs -p ./mergedprof/PROFILE.db -c contigs.db -C MAXBIN2 --driver maxbin2 --just-do-it --log-file log-maxbin2

#anvi-summarize -p ./mergedprof/PROFILE.db -c contigs.db -o SUMMARY_MAXBIN2 -C MAXBIN2

# MAGs quality estimation and visualisation 

#cd /work_beegfs/sunam227/metagenomics/0_raw_reads/clean
#anvi-estimate-genome-completeness -c contigs.db -p ./mergedprof/PROFILE.db -C METABAT2
#anvi-estimate-genome-completeness -p ./mergedprof/PROFILE.db -c contigs.db --list-collections


# Interactive Anvio

#module load gcc12-env/12.1.0
#module load micromamba
#cd $WORK
#micromamba activate .micromamba/envs/00_anvio/

#cd /work_beegfs/sunam227/metagenomics/0_raw_reads/clean
#anvi-interactive -p ./mergedprof/PROFILE.db -c contigs.db -C METABAT2


# DAY 4
# Bin Refinement
#module load gcc12-env/12.1.0
#module load micromamba
#cd $WORK
#micromamba activate .micromamba/envs/00_anvio/


#cd /work_beegfs/sunam227/metagenomics/0_raw_reads/clean
#anvi-summarize -p ./mergedprof/PROFILE.db -c contigs.db --list-collections

#cd /work_beegfs/sunam227/metagenomics/0_raw_reads/clean
#anvi-summarize -c contigs.db -p ./mergedprof/PROFILE.db -C METABAT2 -o ./SUMMARY_METABAT2 --just-do-it



#cd /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/SUMMARY_METABAT2/bin_by_bin

#mkdir ../../ARCHAEA_BIN_REFINEMENT

#cp ./METABAT__10/*.fa ../../ARCHAEA_BIN_REFINEMENT
#cp ./METABAT__36/*.fa ../../ARCHAEA_BIN_REFINEMENT
#cp ./METABAT__8/*.fa ../../ARCHAEA_BIN_REFINEMENT

#module load gcc12-env/12.1.0
#module load micromamba/1.3.1
#micromamba activate 00_gunc

#cd /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/SUMMARY_METABAT2/bin_by_bin/ARCHAEA_BIN_REFINEMENT

#for i in *.fa; do mkdir /work_beegfs/sunam227/metagenomics/0_raw_reads/06_gunc/"$i"_out; done

#for i in *.fa; do
#  gunc run -i "$i" -r $WORK/databases/gunc/gunc_db_progenomes2.1.dmnd --out_dir /work_beegfs/sunam227/metagenomics/0_raw_reads/clean/06_gunc/"$i"_out --threads 12 --detailed_output
#done


cd /work_beegfs/sunam2227/metagenomics/0_raw_reads/06_gunc/METABAT__8-contigs.fa_out
gunc plot -d ./diamond_output/METABAT__#8-contigs.diamond.progenomes_2.1.out -g ./gene_calls/gene_counts.json


# ##----------------- End -------------
module purge
jobinfo